### ISSUE TITLE
Undefined variable in src/js/api/profile/update.js

### ISSUE THREAD

**Issue by Anclagen** [NoroffFEU/social-media-client#30]
Eslint shows id is undefined in updateProfileImage function.
```
G:\My GitHub Portfolio\Course Assignments\Workflow CA\testing\src\js\api\profiles\update.js
  8:62  error  'id' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
````
Looking at it your function the URL is incorrect for updating profile media, should be `${apiPath}/social/profiles/<name>/media`.
Your object from `me` should have the users name defined within. Also remove the whole profile from the fetch body, as media is only expecting banner and avatar to be present in the passed data.

https://github.com/NoroffFEU/social-media-client/blob/f5e3f47446eae70a330b39e90c916d4d8a3f208c/src/js/api/profiles/update.js#L8-L10

Suggested change to function;
```js
  const response = await fetch(`${apiPath}/social/profiles/${me.name}/media`, {
    method: "put",
    body: JSON.stringify({ avatar }),
```

**Comment by Fermain** [comment]
Issue resolved with #58 

Thanks for your contribution!
