### ISSUE TITLE
Unhandled error at login listener

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/social-media-client#60]
There is a caught error when running cypress testing. By adding the wrong login information the login function is not catching the error. The function need to have a try/catch blook. Please fix and patch this before release of the code.

**Comment by Fermain** [comment]
Hi, please could you point to a file or line number to help narrow down the issue

**Comment by Fermain** [comment]
This is intended behaviour, as the responsibility for catching/handling this error is with the UI, at `/src/js/listeners/auth/login.js:10`.

This is the correct place for the error to be caught and represents a valid issue. Please update the title of your issue:

> Unhandled error at login listener
