### ISSUE TITLE
Error running Unit testing

### ISSUE THREAD

**Issue by Christonn93** [NoroffFEU/social-media-client#61]
![image](https://user-images.githubusercontent.com/46559129/200802588-f078dc94-67b2-4705-96fb-98b85a75bec6.png)
With this line of code added in the unit testing the test is failing. 
![image](https://user-images.githubusercontent.com/46559129/200802889-c017718f-a033-4605-b3dd-32b006631f8b.png)

```
 PASS  src/js/api/auth/logout.test.js
 PASS  src/js/api/posts/create.test.js  
 PASS  src/js/storage/index.test.js     
 FAIL  src/js/api/auth/login.test.js
  ● Login › Success

    All is not good! Take a nice coffee and start working on it

      18 |   }
      19 |
    > 20 |   throw new Error(response.statusText)
         |         ^
      21 | }

      at login (src/js/api/auth/login.js:20:9)
      at Object.<anonymous> (src/js/api/auth/login.test.js:48:18)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 12 passed, 13 total
Snapshots:   0 total
Time:        4.184 s
Ran all test suites.
```

Without this all test is passing. 
![image](https://user-images.githubusercontent.com/46559129/200803030-6cae6da3-23a5-4791-aa4c-72842aa021a5.png)

**Comment by Fermain** [comment]
It is not clear from your test description which case this is meant to cover. Fetch is primed for failure, but the test description is "Login it Success". So are you testing for success or failure?

The value of `data` is not visible in your example.

**Comment by Christonn93** [comment]
Thanks for pointing that out. I must have forgotten to change the case. Its now sorted out. 
![image](https://user-images.githubusercontent.com/46559129/200807389-0ee77fdd-070f-46a1-8b05-7cb9e459ab3d.png)

Data value is this: 
![image](https://user-images.githubusercontent.com/46559129/200807343-322bd9c4-47c4-4d24-b40b-f13d880637fa.png)

**Comment by Fermain** [comment]
If you are expecting failure, then the result will not be a profile object - it will probably be `nullish`

**Comment by Christonn93** [comment]
the issue lays in the section of the script that is located  at login (src/js/api/auth/login.js:20:9)

``` 
> 20 |   throw new Error(response.statusText)
         |         ^
 ```
 
![image](https://user-images.githubusercontent.com/46559129/200811149-8cd4cda4-7333-4b9f-a033-624ddf4ed4d3.png)

**Comment by Fermain** [comment]
I don't see why this is an issue. If the details are not valid the function throws an error - this is as intended and not unusual.

The result of a failed login is an error, so you should expect to throw. This is not an issue with the codebase.
