### ISSUE TITLE
missing . in href

### ISSUE THREAD

**Issue by puggen1** [NoroffFEU/social-media-client#73]
#### there is some places that is missing the . in href path
example: 
in src/js/templates/post/actions.js line 19
```
    viewButton.href = `/?view=post&postId=${post.id}`
```
suggested change:
```
    viewButton.href = `./?view=post&postId=${post.id}`
```

this also applies to:
src/js/templates/post/header.js line 9
src/js/templates/post/media.js line 11
src/js/templates/profile/button.js line 7
src/js/templates/profile/thumbnail.js line 4

maybe also 
src/js/listeners/auth/login.js line 13

**Comment by Fermain** [comment]
Thanks for reporting this issue, this will be patched today.
