### ISSUE TITLE
Login form modal closes on invalid input

### ISSUE THREAD

**Issue by Anclagen** [NoroffFEU/social-media-client#77]
When submitting the login form, with invalid details, or invalid inputs the login form modal closes.  Perhaps remove `data-bs-dismiss="modal"` from the button element to prevent it closing.

https://github.com/NoroffFEU/social-media-client/blob/7c917f213c9f7b35c6bce15c87782a5beb84569c/index.html#L89

**Comment by Fermain** [comment]
Related to #90 

Resolved in [891e6b8](https://github.com/NoroffFEU/social-media-client/commit/891e6b887170b114ebfa88bf1264ab8b2e81b444)
